server:
  port: 8082

spring:
  application:
    name: city-service
  datasource:
    url: jdbc:h2:mem:city
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

isa:
  citizen-service:
    url: http://localhost:8081/
    url.delete: /cities/{id}
    url.put: /cities/{id}
    url.post: /cities